package com.mycompany.heap.test;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

public class Ui extends javax.swing.JFrame {
    ZeroList<ZeroList<Integer>> tar_us_lst = new ZeroList<>();
    ZeroList<ZeroList<Integer>> main_us_lst = new ZeroList<>();
    ZeroList<ZeroList<String>> movie_lst = new ZeroList<>();

    public Ui() {
        initComponents();
        csvRead<Integer> csvInt = new csvRead<>();
        csvRead<String> csvString = new csvRead<>();

        csvInt.readFileInt("./data/target_user.csv", tar_us_lst);
        csvInt.readFileInt("./data/main_data.csv", main_us_lst);

        csvString.readFile("./data/movies.csv", movie_lst);

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        csvInt.insert(tar_us_lst, 0, model);
        JCB_User_Select.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPN_TargetUser_Selected = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JCB_User_Select = new javax.swing.JComboBox<>();
        JL_X = new javax.swing.JLabel();
        JTF_X_Selected_Value = new javax.swing.JTextField();
        JL_K = new javax.swing.JLabel();
        JTF_K_Selected_Value = new javax.swing.JTextField();
        JB_Get_Selected_Recommendation = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JLS_Selected_Result = new javax.swing.JList<>();
        JPN_TargetUser_Insert = new javax.swing.JPanel();
        JCB_First_Movie = new javax.swing.JComboBox<>();
        JCB_Second_Movie = new javax.swing.JComboBox<>();
        JCB_Third_Movie = new javax.swing.JComboBox<>();
        JCB_Fourth_Movie = new javax.swing.JComboBox<>();
        JCB_Fifth_Movie = new javax.swing.JComboBox<>();
        JTF_First_Movie_Value = new javax.swing.JTextField();
        JTF_Second_Movie_Value = new javax.swing.JTextField();
        JTF_Third_Movie_Value = new javax.swing.JTextField();
        JTF_Fourth_Movie_Value = new javax.swing.JTextField();
        JTF_Fifth_Movie_Value = new javax.swing.JTextField();
        JTF_X_Insert_Value = new javax.swing.JTextField();
        JTF_K_Insert_Value = new javax.swing.JTextField();
        JL_X1 = new javax.swing.JLabel();
        JL_K1 = new javax.swing.JLabel();
        JB_Get_Insert_Recommendation = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JLS_Insert_Result = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Target User:");

        JL_X.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JL_X.setText("X:");

        JL_K.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JL_K.setText("K:");

        JB_Get_Selected_Recommendation.setText("Get Recommendations");
        JB_Get_Selected_Recommendation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                get_recomended(evt);
            }
        });

        jScrollPane3.setViewportView(JLS_Selected_Result);

        javax.swing.GroupLayout JPN_TargetUser_SelectedLayout = new javax.swing.GroupLayout(JPN_TargetUser_Selected);
        JPN_TargetUser_Selected.setLayout(JPN_TargetUser_SelectedLayout);
        JPN_TargetUser_SelectedLayout.setHorizontalGroup(
                JPN_TargetUser_SelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JPN_TargetUser_SelectedLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JCB_User_Select, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                .addComponent(JL_X, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_SelectedLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(JB_Get_Selected_Recommendation,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 157,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                                .addComponent(JTF_X_Selected_Value,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(JL_K,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(JTF_K_Selected_Value,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(160, Short.MAX_VALUE)));
        JPN_TargetUser_SelectedLayout.setVerticalGroup(
                JPN_TargetUser_SelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(JPN_TargetUser_SelectedLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(JCB_User_Select, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPN_TargetUser_SelectedLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(JPN_TargetUser_SelectedLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JL_K)
                                                        .addComponent(JTF_K_Selected_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_SelectedLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JTF_X_Selected_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 21,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JL_X))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JB_Get_Selected_Recommendation)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 262,
                                                Short.MAX_VALUE)
                                        .addContainerGap()));

        jTabbedPane1.addTab("Selected Part", JPN_TargetUser_Selected);

        JL_X1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JL_X1.setText("X:");

        JL_K1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JL_K1.setText("K:");

        JB_Get_Insert_Recommendation.setText("Get Recommendations");

        jScrollPane4.setViewportView(JLS_Insert_Result);

        javax.swing.GroupLayout JPN_TargetUser_InsertLayout = new javax.swing.GroupLayout(JPN_TargetUser_Insert);
        JPN_TargetUser_Insert.setLayout(JPN_TargetUser_InsertLayout);
        JPN_TargetUser_InsertLayout.setHorizontalGroup(
                JPN_TargetUser_InsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JPN_TargetUser_InsertLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JPN_TargetUser_InsertLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                        .addComponent(JCB_First_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(JTF_First_Movie_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                        .addComponent(JCB_Second_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(JTF_Second_Movie_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                        .addComponent(JCB_Third_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(JTF_Third_Movie_Value)))
                                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                .addComponent(JCB_Fourth_Movie, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JTF_Fourth_Movie_Value,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(JCB_Fifth_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                JPN_TargetUser_InsertLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(JL_K1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(JL_X1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                23,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(JTF_X_Insert_Value,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(JTF_Fifth_Movie_Value,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 245,
                                                                Short.MAX_VALUE)
                                                        .addComponent(JTF_K_Insert_Value)
                                                        .addComponent(JB_Get_Insert_Recommendation,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(13, Short.MAX_VALUE)));
        JPN_TargetUser_InsertLayout.setVerticalGroup(
                JPN_TargetUser_InsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JPN_TargetUser_InsertLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4)
                                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_First_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JTF_First_Movie_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_Second_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JTF_Second_Movie_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_Third_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JTF_Third_Movie_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_Fourth_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JTF_Fourth_Movie_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_Fifth_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JTF_Fifth_Movie_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(JL_X1)
                                                        .addComponent(JTF_X_Insert_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JTF_K_Insert_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JL_K1))
                                                .addGap(18, 18, 18)
                                                .addComponent(JB_Get_Insert_Recommendation)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));

        jTabbedPane1.addTab("Insert Part", JPN_TargetUser_Insert);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING));

        jTabbedPane1.getAccessibleContext().setAccessibleName("Main_Part");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wriet_to_list(MaxHeap<Distance> reco) {
        DefaultListModel<String> dlm = new DefaultListModel<>();

        reco.addEl(dlm);
        JLS_Selected_Result.setModel(dlm);

    }

    private void get_recomended(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_get_recomended

        MaxHeap<Distance> user_reco = new MaxHeap<>(Integer.parseInt(JTF_X_Selected_Value.getText() + ""));
        MaxHeap<Distance> reco = new MaxHeap<>(
                Integer.parseInt(JTF_X_Selected_Value.getText() + "")
                        * Integer.parseInt(JTF_K_Selected_Value.getText() + ""));
        CosSimilarity cs = new CosSimilarity();
        int sel_index = JCB_User_Select.getSelectedIndex();
        Node<ZeroList<Integer>> tmp_tar = tar_us_lst.root;
        for (int i = 0; i < sel_index; i++) {
            tmp_tar = tmp_tar.next;
        }
        Node<ZeroList<Integer>> tmp_main = main_us_lst.root;

        while (tmp_main != null) {
            user_reco.insert(new Distance(tmp_main.data, cs.calculateCosSim(tmp_tar.data, tmp_main.data)));
            tmp_main = tmp_main.next;
        }

        wriet_to_list(user_reco);
    }// GEN-LAST:event_get_recomended

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Get_Insert_Recommendation;
    private javax.swing.JButton JB_Get_Selected_Recommendation;
    private javax.swing.JComboBox<String> JCB_Fifth_Movie;
    private javax.swing.JComboBox<String> JCB_First_Movie;
    private javax.swing.JComboBox<String> JCB_Fourth_Movie;
    private javax.swing.JComboBox<String> JCB_Second_Movie;
    private javax.swing.JComboBox<String> JCB_Third_Movie;
    private javax.swing.JComboBox<String> JCB_User_Select;
    private javax.swing.JList<String> JLS_Insert_Result;
    private javax.swing.JList<String> JLS_Selected_Result;
    private javax.swing.JLabel JL_K;
    private javax.swing.JLabel JL_K1;
    private javax.swing.JLabel JL_X;
    private javax.swing.JLabel JL_X1;
    private javax.swing.JPanel JPN_TargetUser_Insert;
    private javax.swing.JPanel JPN_TargetUser_Selected;
    private javax.swing.JTextField JTF_Fifth_Movie_Value;
    private javax.swing.JTextField JTF_First_Movie_Value;
    private javax.swing.JTextField JTF_Fourth_Movie_Value;
    private javax.swing.JTextField JTF_K_Insert_Value;
    private javax.swing.JTextField JTF_K_Selected_Value;
    private javax.swing.JTextField JTF_Second_Movie_Value;
    private javax.swing.JTextField JTF_Third_Movie_Value;
    private javax.swing.JTextField JTF_X_Insert_Value;
    private javax.swing.JTextField JTF_X_Selected_Value;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
