package com.mycompany.heap.test;

import java.util.Random;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;

public class Ui extends javax.swing.JFrame {
    ZeroList<ZeroList<Integer>> tar_us_lst = new ZeroList<>();
    ZeroList<ZeroList<Integer>> main_us_lst = new ZeroList<>();
    ZeroList<ZeroList<String>> movie_lst = new ZeroList<>();

    ZeroList<Integer> user_vector = new ZeroList<Integer>();

    public Ui() {
        initComponents();
        csvRead<Integer> csvInt = new csvRead<>();
        csvRead<String> csvString = new csvRead<>();

        csvInt.readFileInt("./data/target_user.csv", tar_us_lst);
        csvInt.readFileInt("./data/main_data.csv", main_us_lst);

        csvString.readFile("./data/movies.csv", movie_lst);
        movie_lst.root.data.print();
        System.out.println(movie_lst.root.data.root.next.data);

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        csvInt.insert(tar_us_lst, 0, model);
        JCB_User_Select.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPN_TargetUser_Selected = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JCB_User_Select = new javax.swing.JComboBox<>();
        JL_X = new javax.swing.JLabel();
        JTF_X_Selected_Value = new javax.swing.JTextField();
        JL_K = new javax.swing.JLabel();
        JTF_K_Selected_Value = new javax.swing.JTextField();
        JB_Get_Selected_Recommendation = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JLS_Selected_Result = new javax.swing.JList<>();
        JPN_TargetUser_Insert = new javax.swing.JPanel();
        JCB_First_Movie = new javax.swing.JComboBox<>();
        JCB_Second_Movie = new javax.swing.JComboBox<>();
        JCB_Third_Movie = new javax.swing.JComboBox<>();
        JCB_Fourth_Movie = new javax.swing.JComboBox<>();
        JCB_Fifth_Movie = new javax.swing.JComboBox<>();
        JTF_X_Insert_Value = new javax.swing.JTextField();
        JTF_K_Insert_Value = new javax.swing.JTextField();
        JL_X1 = new javax.swing.JLabel();
        JL_K1 = new javax.swing.JLabel();
        JB_Get_Insert_Recommendation = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JLS_Insert_Result = new javax.swing.JList<>();
        JS_1_MOVIE_VAL = new javax.swing.JSpinner();
        JS_2_MOVİE_VAL = new javax.swing.JSpinner();
        JS_3_MOVİE_VAL = new javax.swing.JSpinner();
        JS_4_MOVİE_VAL = new javax.swing.JSpinner();
        JS_5_MOVİE_VAL = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Target User:");

        JL_X.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JL_X.setText("X:");

        JL_K.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JL_K.setText("K:");

        JB_Get_Selected_Recommendation.setText("Get Recommendations");
        JB_Get_Selected_Recommendation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                get_recomended(evt);
            }
        });

        jScrollPane3.setViewportView(JLS_Selected_Result);

        javax.swing.GroupLayout JPN_TargetUser_SelectedLayout = new javax.swing.GroupLayout(JPN_TargetUser_Selected);
        JPN_TargetUser_Selected.setLayout(JPN_TargetUser_SelectedLayout);
        JPN_TargetUser_SelectedLayout.setHorizontalGroup(
                JPN_TargetUser_SelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JPN_TargetUser_SelectedLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JCB_User_Select, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                .addComponent(JL_X, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_SelectedLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(JB_Get_Selected_Recommendation,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 157,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                                .addComponent(JTF_X_Selected_Value,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(JL_K,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(JTF_K_Selected_Value,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE)));
        JPN_TargetUser_SelectedLayout.setVerticalGroup(
                JPN_TargetUser_SelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(JPN_TargetUser_SelectedLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(JCB_User_Select, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPN_TargetUser_SelectedLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(JPN_TargetUser_SelectedLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JL_K)
                                                        .addComponent(JTF_K_Selected_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_SelectedLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JTF_X_Selected_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 21,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JL_X))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JB_Get_Selected_Recommendation)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                JPN_TargetUser_SelectedLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 262,
                                                Short.MAX_VALUE)
                                        .addContainerGap()));

        jTabbedPane1.addTab("Selected Part", JPN_TargetUser_Selected);

        JL_X1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JL_X1.setText("X:");

        JL_K1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JL_K1.setText("K:");

        JB_Get_Insert_Recommendation.setText("Get Recommendations");
        JB_Get_Insert_Recommendation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JB_Get_Insert_RecommendationMousePressed(evt);
            }
        });

        jScrollPane4.setViewportView(JLS_Insert_Result);

        JS_1_MOVIE_VAL.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        JS_2_MOVİE_VAL.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        JS_3_MOVİE_VAL.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        JS_4_MOVİE_VAL.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        JS_5_MOVİE_VAL.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout JPN_TargetUser_InsertLayout = new javax.swing.GroupLayout(JPN_TargetUser_Insert);
        JPN_TargetUser_Insert.setLayout(JPN_TargetUser_InsertLayout);
        JPN_TargetUser_InsertLayout.setHorizontalGroup(
                JPN_TargetUser_InsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JPN_TargetUser_InsertLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(JL_K1, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JL_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(JTF_X_Insert_Value,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 245,
                                                                Short.MAX_VALUE)
                                                        .addComponent(JTF_K_Insert_Value)
                                                        .addComponent(JB_Get_Insert_Recommendation,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                        .addGroup(JPN_TargetUser_InsertLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(JCB_Fifth_Movie, 0,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(JCB_Fourth_Movie,
                                                                        javax.swing.GroupLayout.Alignment.LEADING, 0,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(JCB_Second_Movie,
                                                                        javax.swing.GroupLayout.Alignment.LEADING, 0,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(JCB_Third_Movie,
                                                                        javax.swing.GroupLayout.Alignment.LEADING, 0,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(JCB_First_Movie,
                                                                        javax.swing.GroupLayout.Alignment.LEADING, 0,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(JPN_TargetUser_InsertLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(JS_1_MOVIE_VAL,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(JS_2_MOVİE_VAL,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(JS_3_MOVİE_VAL,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(JS_4_MOVİE_VAL,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(JS_5_MOVİE_VAL,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(25, 25, 25)))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE)));
        JPN_TargetUser_InsertLayout.setVerticalGroup(
                JPN_TargetUser_InsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JPN_TargetUser_InsertLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4)
                                        .addGroup(JPN_TargetUser_InsertLayout.createSequentialGroup()
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_First_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JS_1_MOVIE_VAL,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_Second_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JS_2_MOVİE_VAL,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_Third_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JS_3_MOVİE_VAL,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_Fourth_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JS_4_MOVİE_VAL,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCB_Fifth_Movie,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JS_5_MOVİE_VAL,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(JL_X1)
                                                        .addComponent(JTF_X_Insert_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(JPN_TargetUser_InsertLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JTF_K_Insert_Value,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JL_K1))
                                                .addGap(18, 18, 18)
                                                .addComponent(JB_Get_Insert_Recommendation)
                                                .addGap(0, 18, Short.MAX_VALUE)))
                                .addContainerGap()));

        jTabbedPane1.addTab("Insert Part", JPN_TargetUser_Insert);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING));

        jTabbedPane1.getAccessibleContext().setAccessibleName("Main_Part");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ZeroList<ZeroList<String>> film_lst_combo = new ZeroList<>();

    private void JB_Get_Insert_RecommendationMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_JB_Get_Insert_RecommendationMousePressed
        // ? diğer panelde tavsiyelere getire basınca
        // ? film_lst_combo:
        // ! spinnerlrın İ lerini değiştir
        ZeroList<String> index = film_lst_combo.root.data;

        Node<ZeroList<String>> m_index = film_lst_combo.root;
        int[] sellected_film_start = { Integer.parseInt(JS_1_MOVIE_VAL.getValue().toString()),
                Integer.parseInt(JS_2_MOVİE_VAL.getValue().toString()),
                Integer.parseInt(JS_3_MOVİE_VAL.getValue().toString()),
                Integer.parseInt(JS_4_MOVİE_VAL.getValue().toString()),
                Integer.parseInt(JS_5_MOVİE_VAL.getValue().toString()) };
        int[] sellected_film_index = { JCB_First_Movie.getSelectedIndex(),
                JCB_Second_Movie.getSelectedIndex(),
                JCB_Third_Movie.getSelectedIndex(),
                JCB_Fourth_Movie.getSelectedIndex(),
                JCB_Fifth_Movie.getSelectedIndex() };
        for (int i = 0; i < 5; i++) {
            Node<String> flm_nod = m_index.data.root;
            for (int j = 0; j < sellected_film_index[i]; j++) {
                flm_nod = flm_nod.next;
            }
            user_vector.setIndex(flm_nod.film_index);
            user_vector.insert(sellected_film_start[i]);
            m_index = m_index.next;
        }



        MaxHeap2<Distance> user_reco = new MaxHeap2<>(Integer.parseInt(JTF_X_Insert_Value.getText() + ""));

        CosSimilarity cs = new CosSimilarity();
        //int sel_index = JCB_User_Select.getSelectedIndex();
        
       // Node<ZeroList<Integer>> tmp_tar = tar_us_lst.root;

        Node<ZeroList<Integer>> tmp_main = main_us_lst.root;

        while (tmp_main != null) {
            user_reco.insert(new Distance(tmp_main.data, cs.calculateCosSim(user_vector, tmp_main.data)));
            tmp_main = tmp_main.next;
        }
        wriet_to_list(fillFilm(user_reco, Integer.parseInt(JTF_K_Insert_Value.getText() + "")),JLS_Insert_Result);

        // for(int i = 0; i < )
        // user_vector.setIndex(ran);
        // user_vector.insert(Integer.parseInt(mv_lst.data.root.toString()));

    } // GEN-LAST:event_JB_Get_Insert_RecommendationMousePressed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTabbedPane1MousePressed
        // ? diğer panele geçince
        // ? 5000 film içinden rast gele film seç
        Random r = new Random();
        int ran = r.nextInt(200);
        Node<ZeroList<String>> mv_lst = movie_lst.root;
        ZeroList<String> films;
        for (int k = 0; k < 5; k++) {
            films = new ZeroList<>();
            for (int i = 0; i < 5; i++) {
                for (int j = 0; j < ran; j++) {
                    mv_lst = mv_lst.next;
                }
                Node<String> t = films.insert(mv_lst.data.root.next.data);
                t.film_index = Integer.parseInt(mv_lst.data.root.data);
                ran += r.nextInt(20);
            }
            film_lst_combo.insert(films);
        }
        JComboBox [] vcm_arr={
            JCB_First_Movie,
                JCB_Second_Movie,
                JCB_Third_Movie,
                JCB_Fourth_Movie,
                JCB_Fifth_Movie
        };
        Node<ZeroList<String>> t=film_lst_combo.root;
        for (int i = 0; i < vcm_arr.length; i++) {
            add_movie_in_combobox(t.data,vcm_arr[i]);
            t=t.next;
        }

        // JCB_Fifth_Movie.sete
    }// GEN-LAST:event_jTabbedPane1MousePressed

    private void add_movie_in_combobox(ZeroList<String> movies, JComboBox jcb) {
        Node<String> temp = movies.root;
        while (temp != null) {
            jcb.addItem(temp.data);
            temp = temp.next;
        }
    }

    private void wriet_to_list(ZeroList<Integer> zl,JList jls) {
        // ? zl = 5 , 3 , 6 , 9
        System.out.println("----------baş----------------------");
        zl.print();
        System.out.println("----------baş----------------------");
        // 7,15,27 movie_lst
        // ZeroList<Integer> index = zl;
        Node<Integer> idx_n = zl.root;
        DefaultListModel<String> dlm = new DefaultListModel<>();

        Node<ZeroList<String>> table_i = movie_lst.root;
        while (idx_n != null) {
            while (table_i != null) {
                int index_table = Integer.parseInt(table_i.data.root.data);
                if (idx_n.data == index_table) {
                    dlm.addElement(table_i.data.root.next.data);
                    System.out.println("-----------------son liste yazma---------------");
                    break;
                }
                table_i = table_i.next;
            }
            table_i = movie_lst.root;
            idx_n = idx_n.next;
        }
        // reco.addEl(dlm);
        jls.setModel(dlm);

    }

    private ZeroList<Integer> fillFilm(MaxHeap2<Distance> user_reco, int k) {
        // 5 tane kullanıcı capasity içinde
        // ZeroList<MaxHeap2<Integer>> film_index_lst = new ZeroList<>();//!
        // kullancağımız

        Node<Distance> usr_rc_n = user_reco.heap.root;
        ZeroList<Integer> result = new ZeroList<>();
        System.out.println("--------------------------------");
        result.print();
        System.out.println("--------------------------------");
        int idx = 0;
        for (int i = 0; i < user_reco.capacity; i++) {

            MaxHeap2<Distance> star_heap = new MaxHeap2<>(k);
            Node<Integer> tmp_vetor = usr_rc_n.data.vektor.root.next;

            while (tmp_vetor != null) {
                star_heap.insert(new Distance(idx++, tmp_vetor.data));
                tmp_vetor = tmp_vetor.next;
            }
            idx = 0;
            Node<Distance> star_node = star_heap.heap.root;
            for (int j = 0; j < k; j++) {
                result.insert(star_node.data.index);
                star_node = star_node.next;
            }
            // film_index_lst.insert(tmp_heap);
            usr_rc_n = usr_rc_n.next;
        }
        System.out.println("--------------------------------");
        result.print();
        System.out.println("--------------------------------");
        return result;
    }

    private void get_recomended(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_get_recomended

        MaxHeap2<Distance> user_reco = new MaxHeap2<>(Integer.parseInt(JTF_X_Selected_Value.getText() + ""));

        CosSimilarity cs = new CosSimilarity();
        int sel_index = JCB_User_Select.getSelectedIndex();

        Node<ZeroList<Integer>> tmp_tar = tar_us_lst.root;
        for (int i = 0; i < sel_index; i++) {
            tmp_tar = tmp_tar.next;
        }
        Node<ZeroList<Integer>> tmp_main = main_us_lst.root;

        while (tmp_main != null) {
            user_reco.insert(new Distance(tmp_main.data, cs.calculateCosSim(tmp_tar.data, tmp_main.data)));
            tmp_main = tmp_main.next;
        }
        wriet_to_list(fillFilm(user_reco, Integer.parseInt(JTF_K_Selected_Value.getText() + "")),JLS_Selected_Result);
        user_reco.print();
        // wriet_to_list(user_reco);
    }// GEN-LAST:event_get_recomended

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Get_Insert_Recommendation;
    private javax.swing.JButton JB_Get_Selected_Recommendation;
    private javax.swing.JComboBox<String> JCB_Fifth_Movie;
    private javax.swing.JComboBox<String> JCB_First_Movie;
    private javax.swing.JComboBox<String> JCB_Fourth_Movie;
    private javax.swing.JComboBox<String> JCB_Second_Movie;
    private javax.swing.JComboBox<String> JCB_Third_Movie;
    private javax.swing.JComboBox<String> JCB_User_Select;
    private javax.swing.JList<String> JLS_Insert_Result;
    private javax.swing.JList<String> JLS_Selected_Result;
    private javax.swing.JLabel JL_K;
    private javax.swing.JLabel JL_K1;
    private javax.swing.JLabel JL_X;
    private javax.swing.JLabel JL_X1;
    private javax.swing.JPanel JPN_TargetUser_Insert;
    private javax.swing.JPanel JPN_TargetUser_Selected;
    private javax.swing.JSpinner JS_1_MOVIE_VAL;
    private javax.swing.JSpinner JS_2_MOVİE_VAL;
    private javax.swing.JSpinner JS_3_MOVİE_VAL;
    private javax.swing.JSpinner JS_4_MOVİE_VAL;
    private javax.swing.JSpinner JS_5_MOVİE_VAL;
    private javax.swing.JTextField JTF_K_Insert_Value;
    private javax.swing.JTextField JTF_K_Selected_Value;
    private javax.swing.JTextField JTF_X_Insert_Value;
    private javax.swing.JTextField JTF_X_Selected_Value;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
